image: jangrewe/gitlab-ci-android

stages:
  - build

before_script:
  - export GRADLE_USER_HOME=$(pwd)/.gradle
  - chmod +x ./gradlew

cache:
  key: ${CI_PROJECT_ID}
  paths:
  - .gradle/

debug:
  stage: build
  except:
    - release
  script:
    - ./gradlew assembleDebug
  artifacts:
    paths:
    - app/build/outputs/apk/app-debug.apk

release:
  stage: build
  only:
    - release
  script:
    - ./gradlew assembleRelease
  artifacts:
    paths:
    - app/build/outputs/apk/app-release.apk
