image: jangrewe/gitlab-ci-android

variables:
  ANDROID_COMPILE_SDK: "27"
  APP_NAME: "ScreenLocker"

cache:
  key: ${CI_PROJECT_ID}
  paths:
    - .gradle/

stages:
  - build
  - package

before_script:
  - export GRADLE_USER_HOME=$(pwd)/.gradle
  - chmod +x ./gradlew

build_debug:
  stage: build
#  except:
#    - release
  script:
    - ./gradlew assembleDebug
#  artifacts:
#    paths:
#    - app/build/outputs/apk/debug/app-debug.apk

build_release:
  stage: build
#  only:
#    - release
  script:
    - ./gradlew assembleRelease
#  artifacts:
#    paths:
#    - app/build/outputs/apk/release/app-release.apk
