image: jangrewe/gitlab-ci-android

variables:
  ANDROID_COMPILE_SDK: "27"
  APP_NAME: "ScreenLocker"
  MOUNT_POINT: /builds/$CI_PROJECT_PATH/mnt

cache:
  key: ${CI_PROJECT_ID}
  paths:
    - .gradle/

stages:
  - build
  - package

before_script:
  - export GRADLE_USER_HOME=$(pwd)/.gradle
  - chmod +x ./gradlew

build_debug:
  stage: build
  #  except:
  #    - release
  script:
    - ./gradlew assembleDebug
  artifacts:
    paths:
      - app/build/outputs

#build_release:
#  stage: build
#  only:
#    - release
#  script:
#    - ./gradlew assembleRelease
#  artifacts:
#    paths:
#    - app/build/outputs/apk/release/app-release.apk

.package_template: &package_template_def
  before_script:
    - export VERSION_NAME=`egrep '^[[:blank:]]+versionName[[:blank:]]'  app/build.gradle | awk '{print $2}' | sed s/\"//g`
    - export VERSION_CODE=`egrep '^[[:blank:]]+versionCode[[:blank:]]'  app/build.gradle | awk '{print $2}'`
    - mkdir -p deliverables

    # Store some information about the build
    - touch ./deliverables/info.txt
    - echo "Build date          $(date)"                >> ./deliverables/info.txt
    - echo "App version name    ${VERSION_NAME}"        >> ./deliverables/info.txt
    - echo "App version code    ${VERSION_CODE}"        >> ./deliverables/info.txt
    - echo "Git branch          ${CI_COMMIT_REF_NAME}"  >> ./deliverables/info.txt
    - echo "Git commit          ${CI_COMMIT_SHA}"       >> ./deliverables/info.txt
    - echo "Gitlab pipeline     ${CI_PIPELINE_ID}"      >> ./deliverables/info.txt

package_debug:
  <<: *package_template_def
  stage: package
  environment: Development
  #  only:
  #    - develop
  script:
    - mv app/build/outputs/apk/debug/app-debug.apk ./deliverables/ScreenLocker-v$VERSION_NAME-$VERSION_CODE-debug.apk
    - java -Djava.library.path=/tools/lib64 -jar /tools/signapk.jar /tools/platform.x509.pem /tools/platform.pk8 ./deliverables/ScreenLocker-v$VERSION_NAME-$VERSION_CODE-debug.apk ./deliverables/ScreenLocker-v$VERSION_NAME-$VERSION_CODE-debug-signed.apk
  artifacts:
    #    expire_in: 7 days
    paths:
      - deliverables
  dependencies:
    - build_debug
